version: '3.8'
services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
    # volumes:
    #   - ./frontend:/app
    restart: always
    networks:
      - app
    container_name: frontend
    
  backend:
    build: backend
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    # volumes:
    #   - ./backend:/app
    restart: always
    networks:
      - app
    container_name: backend

  db:
    image: postgres:16
    container_name: db_app
    env_file:
      - docker.env
    expose:
      - 5432
    networks:
      - app

networks:
  app:
    driver: bridge